#pragma once

const char* tracks[] = { "MUSIC/THEME.WAV", "MUSIC/CLEANIN.WAV" ,"MUSIC/SAVIN.WAV" ,"MUSIC/MAGICCUT.WAV", "MUSIC/RGBTHEME.WAV", "MUSIC/TITLE.WAV", "MUSIC/ONOUROWN.WAV" };
int trackCount = 7;

enum State { OFF, WANDON, BOOTING, IDLE, POWERDOWN, FIRING_HEAT, FIRING_NOHEAT, FIRING_OHWARNING, OVERHEAT, FIRING_STOP, MUSIC_MODE };

