; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<*> -<.git/> -<Pack.cpp>
; PlatformIO should auto-detect the upload port for the device.  If not, you can specify the port below.
; upload_port = COM5

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<*> -<.git/> -<Wand.cpp>
; PlatformIO should auto-detect the upload port for the device.  If not, you can specify the port below.
; upload_port = COM5

[platformio]
description = Proton Pack Software - The Teensy 4.0 build is for the main pack electronics, and the ESP32 build is for the wand